# =============================================
# Connexion MySQL
# Modifier ces valeurs selon votre installation
# =============================================
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/events_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
db.username=root
db.password=azerty
# =============================================
# Hibernate
# =============================================
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# update  : met à jour le schéma sans supprimer les données
# create  : recrée les tables à chaque démarrage (pour le TP)
# validate: vérifie sans modifier
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
